### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by roachhd** [roachhd/big-ass-resource-list#7]
- [ ] dark/ light switch for style
- [ ] add css resources
- [ ] tidy format, and order
- [ ] add FORK ME css ribbon 
- [ ] add GITHUB buttons, star and fork
- [ ] add a haker news button
- [ ] add octocat pic, shadowy 
- [ ] add a little blurb
- [ ] add a footer with heart and Twitter, me! & blog links 
- [ ] colophon
